---
title: "Data"
author: "Zach Keefer"
date: "12/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readxl)
library(patchwork)
```



```{r}
##Reading in the flu data.  Files were too large to query all at once
file_df = tibble(file_path = list.files('./data/', pattern = '*.csv', full.names = TRUE), file_name = basename(file_path))

read_data = function(data){
  
  read_csv(file = data, skip = 3)
  
}

flu_df = file_df %>%
  mutate(obs = map(file_path, read_data))
```


```{r}
##Binding the data rows
flu_df = flu_df %>%  
  janitor::clean_names() %>% 
  ##Creating an epiweek variable that is ordinal
  mutate(week = as.character(week),
         week = ifelse(week == "1", "01", week),
         week = ifelse(week == "2", "02", week),
         week = ifelse(week == "3", "03", week),
         week = ifelse(week == "4", "04", week),
         week = ifelse(week == "5", "05", week),
         week = ifelse(week == "6", "06", week),
         week = ifelse(week == "7", "07", week),
         week = ifelse(week == "8", "08", week),
         week = ifelse(week == "9", "09", week),
         epiweek = str_c(year, week, sep = "."),
         epiweek = as.numeric(epiweek)) 
```

```{r}
tidy_flu = flu_df %>% 
  ##Tidy flu data set to use for visualizations
  group_by(fluregion, epiweek) %>% 
  summarize(cases = sum(all_inf),
            h1 = sum(ah1),
            h3 = sum(ah3),
            h5 = sum(ah5),
            h1n1 = sum(ah1n12009),
            a_total = sum(inf_a),
            b_total = sum(inf_b))
```


```{r}
countries = flu_df %>% 
  ##dataset to use to bind demographic data
  group_by(fluregion, country) %>% 
  summarize(infections = sum(all_inf))
```


Reading in and cleaning demographic data
```{r}
arrival_df = read_excel("./data/arrival_data.xls", skip = 3) %>% 
  janitor::clean_names() %>% 
  select(country, country_code, x2012:x2014) %>% 
  gather(key = year, value = arrivals, x2012:x2014) %>% 
  group_by(country) %>% 
  summarize(mean_arrival = mean(arrivals))
```

```{r}
pop_df = read_excel("./data/pop_data.xls", skip = 3) %>% 
  janitor::clean_names() %>% 
  select(country, country_code, x2012:x2014) %>% 
  gather(key = year, value = pop, x2012:x2014) %>% 
  group_by(country) %>% 
  summarize(mean_pop = mean(pop))
```

```{r}
drs_df = read_excel("./data/dr_per_100k_data.xls") %>% 
  janitor::clean_names() %>% 
  mutate(drs_per_100k = as.numeric(drs_per_100k)) %>% 
  group_by(country) %>% 
  summarize(drs = mean(drs_per_100k))
```

Joining Demo data
```{r}
country_demo = left_join(countries, pop_df, by = "country")

country_demo = left_join(country_demo, arrival_df, by = "country")

country_demo = left_join(country_demo, drs_df, by = "country")
```


Tidy demo data df.
```{r}
flu_region_demo = country_demo %>% 
  group_by(fluregion) %>% 
  summarize(infections = sum(infections),
            population = sum(mean_pop, na.rm = TRUE),
            arrivals = sum(mean_arrival, na.rm = TRUE),
            drs_per_100k = mean(drs, na.rm = TRUE))
```

```{r}
flu_demo_df = left_join(tidy_flu, flu_region_demo, by = "fluregion") %>% 
  mutate(cases_by_1k = (cases*1000)/population)
```



```{r}
flu_demo_df %>% 
  ggplot(aes(x = epiweek, y = cases_by_1k)) +
  geom_line() +
  facet_wrap(~ fluregion)
```



```{r}
tidy_flu_2 = flu_df %>% 
  mutate(week = as.numeric(week),
         year = as.factor(year)) %>% 
  group_by(fluregion, year, week) %>% 
    summarize(cases = sum(all_inf),
            h1 = sum(ah1),
            h3 = sum(ah3),
            h5 = sum(ah5),
            h1n1 = sum(ah1n12009),
            a_total = sum(inf_a),
            b_total = sum(inf_b)) %>% 
  left_join(flu_region_demo, by = "fluregion") %>% 
  mutate(cases_by_1k = (cases*1000)/population)

tidy_flu_2 %>% 
  ggplot(aes(x = week, y = cases_by_1k, color = year)) +
  geom_line() +
  facet_wrap(~ fluregion)
  
```

The zones with the most complete data are North America, Northern Europe, Oceania Melanesia Polynesia, and Temperate South America

```{r}
#Filter flu data for zones of interest
tidy_flu_3 = tidy_flu_2 %>% 
  filter(fluregion %in% c('North America', 'Northern Europe', 'Oceania Melanesia Polynesia', 'Temperate South America', 'Eastern Asia')) 

tidy_flu_3 %>% 
  ggplot(aes(x = week, y = cases_by_1k, color = year)) +
  geom_line() +
  facet_wrap(~ fluregion)
```

Looking at distribution of influenza types and subtypes
```{r}
NoAm = tidy_flu_3 %>% 
  filter(fluregion == 'North America') %>% 
  ggplot() +
  geom_line(aes(x = week, y = h1n1, color = 'H1')) +
  geom_line(aes(x = week, y = h3, color = 'H3')) +
  geom_line(aes(x = week, y = h5, color = 'H5')) + 
  geom_line(aes(x = week, y = b_total, color = 'Type B')) +
  facet_grid(~ year) +
  labs(
    title = 'North America',
    y = 'Cases'
  )

NoEu = tidy_flu_3 %>% 
  filter(fluregion == 'Northern Europe') %>% 
  ggplot() +
  geom_line(aes(x = week, y = h1n1, color = 'H1')) +
  geom_line(aes(x = week, y = h3, color = 'H3')) +
  geom_line(aes(x = week, y = h5, color = 'H5')) +
  geom_line(aes(x = week, y = b_total, color = 'Type B')) +
  facet_grid(~ year) +
  labs(
    title = 'Northern Europe',
    y = 'Cases'
  )

OMP = tidy_flu_3 %>% 
  filter(fluregion == 'Oceania Melanesia Polynesia') %>% 
  ggplot() +
  geom_line(aes(x = week, y = h1n1, color = 'H1')) +
  geom_line(aes(x = week, y = h3, color = 'H3')) +
  geom_line(aes(x = week, y = h5, color = 'H5')) +
  geom_line(aes(x = week, y = b_total, color = 'Type B')) +
  facet_grid(~ year) +
  labs(
    title = 'Oceania Melanesia Polynesia',
    y = 'Cases'
  )

TSA = tidy_flu_3 %>% 
  filter(fluregion == 'Temperate South America') %>% 
  ggplot() +
  geom_line(aes(x = week, y = h1n1, color = 'H1')) +
  geom_line(aes(x = week, y = h3, color = 'H3')) +
  geom_line(aes(x = week, y = h5, color = 'H5')) +
  geom_line(aes(x = week, y = b_total, color = 'Type B')) +
  facet_grid(~ year) +
  labs(
    title = 'Temperate South America',
    y = 'Cases'
  )

EaAs = tidy_flu_3 %>% 
  filter(fluregion == 'Eastern Asia') %>% 
  ggplot() +
  geom_line(aes(x = week, y = h1n1, color = 'H1')) +
  geom_line(aes(x = week, y = h3, color = 'H3')) +
  geom_line(aes(x = week, y = h5, color = 'H5')) +
  geom_line(aes(x = week, y = b_total, color = 'Type B')) +
  facet_grid(~ year) +
  labs(
    title = 'Eastern Asia',
    y = 'Cases'
  )

NoAm / NoEu / OMP / TSA / EaAs
```

Looking at type A subtypes


